# Configurações do Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true

# Propriedades do Fabric
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# API do Fabric - Use uma versão compatível com 1.21.10
fabric_version=0.134.0+1.21.9

# Propriedades do Mod
mod_version=1.0.0
maven_group=com.barium
archives_base_name=barium

# Dependências
modmenu_version=16.0.0-rc.1
cloth_config_version=20.0.149