# Nome mais descritivo para o seu workflow
name: Build Barium Mod

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # A ação oficial do Gradle cuida da validação, caching, setup do Java e permissões.
      # Substitui 3 dos seus passos antigos por 1.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          # Nome mais descritivo para os artefatos
          name: barium-fabric
          path: build/libs/