name: Build Barium Mod

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ação oficial do Gradle que cuida do caching, validação E setup do Java.
      - name: Setup Gradle and Java
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Mod-JARs
          path: build/libs/